
                log_format proxy_debug
        '$remote_addr - [$time_local] '
        '"$request" $status '
        'host="$host" '
        'uri="$uri" '
        'upstream="$upstream_addr" '
        'upstream_status="$upstream_status" '
        'request_time="$request_time" '
        'upstream_response_time="$upstream_response_time"';

    access_log /dev/stdout proxy_debug;

    server {
        listen 9000;
        server_name 127.0.0.1;

        location / {
            root /usr/share/nginx/html;
            index index.html;
            try_files $uri $uri/ =404;
        }

        location /_comentario/ {
            proxy_pass http://comentario:80/_comentario/;
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

    }
